/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.madhouse.ssp.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WinNotice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WinNotice\",\"namespace\":\"com.madhouse.ssp.avro\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"dspid\",\"type\":\"long\"},{\"name\":\"impid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"mediaid\",\"type\":\"long\"},{\"name\":\"adspaceid\",\"type\":\"long\"},{\"name\":\"price\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long time;
  @Deprecated public int status;
  @Deprecated public long dspid;
  @Deprecated public java.lang.String impid;
  @Deprecated public long mediaid;
  @Deprecated public long adspaceid;
  @Deprecated public int price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public WinNotice() {}

  /**
   * All-args constructor.
   */
  public WinNotice(java.lang.Long time, java.lang.Integer status, java.lang.Long dspid, java.lang.String impid, java.lang.Long mediaid, java.lang.Long adspaceid, java.lang.Integer price) {
    this.time = time;
    this.status = status;
    this.dspid = dspid;
    this.impid = impid;
    this.mediaid = mediaid;
    this.adspaceid = adspaceid;
    this.price = price;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return status;
    case 2: return dspid;
    case 3: return impid;
    case 4: return mediaid;
    case 5: return adspaceid;
    case 6: return price;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Long)value$; break;
    case 1: status = (java.lang.Integer)value$; break;
    case 2: dspid = (java.lang.Long)value$; break;
    case 3: impid = (java.lang.String)value$; break;
    case 4: mediaid = (java.lang.Long)value$; break;
    case 5: adspaceid = (java.lang.Long)value$; break;
    case 6: price = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.Long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Integer value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'dspid' field.
   */
  public java.lang.Long getDspid() {
    return dspid;
  }

  /**
   * Sets the value of the 'dspid' field.
   * @param value the value to set.
   */
  public void setDspid(java.lang.Long value) {
    this.dspid = value;
  }

  /**
   * Gets the value of the 'impid' field.
   */
  public java.lang.String getImpid() {
    return impid;
  }

  /**
   * Sets the value of the 'impid' field.
   * @param value the value to set.
   */
  public void setImpid(java.lang.String value) {
    this.impid = value;
  }

  /**
   * Gets the value of the 'mediaid' field.
   */
  public java.lang.Long getMediaid() {
    return mediaid;
  }

  /**
   * Sets the value of the 'mediaid' field.
   * @param value the value to set.
   */
  public void setMediaid(java.lang.Long value) {
    this.mediaid = value;
  }

  /**
   * Gets the value of the 'adspaceid' field.
   */
  public java.lang.Long getAdspaceid() {
    return adspaceid;
  }

  /**
   * Sets the value of the 'adspaceid' field.
   * @param value the value to set.
   */
  public void setAdspaceid(java.lang.Long value) {
    this.adspaceid = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.lang.Integer getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Integer value) {
    this.price = value;
  }

  /** Creates a new WinNotice RecordBuilder */
  public static com.madhouse.ssp.avro.WinNotice.Builder newBuilder() {
    return new com.madhouse.ssp.avro.WinNotice.Builder();
  }
  
  /** Creates a new WinNotice RecordBuilder by copying an existing Builder */
  public static com.madhouse.ssp.avro.WinNotice.Builder newBuilder(com.madhouse.ssp.avro.WinNotice.Builder other) {
    return new com.madhouse.ssp.avro.WinNotice.Builder(other);
  }
  
  /** Creates a new WinNotice RecordBuilder by copying an existing WinNotice instance */
  public static com.madhouse.ssp.avro.WinNotice.Builder newBuilder(com.madhouse.ssp.avro.WinNotice other) {
    return new com.madhouse.ssp.avro.WinNotice.Builder(other);
  }
  
  /**
   * RecordBuilder for WinNotice instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WinNotice>
    implements org.apache.avro.data.RecordBuilder<WinNotice> {

    private long time;
    private int status;
    private long dspid;
    private java.lang.String impid;
    private long mediaid;
    private long adspaceid;
    private int price;

    /** Creates a new Builder */
    private Builder() {
      super(com.madhouse.ssp.avro.WinNotice.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.madhouse.ssp.avro.WinNotice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dspid)) {
        this.dspid = data().deepCopy(fields()[2].schema(), other.dspid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.impid)) {
        this.impid = data().deepCopy(fields()[3].schema(), other.impid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.mediaid)) {
        this.mediaid = data().deepCopy(fields()[4].schema(), other.mediaid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.adspaceid)) {
        this.adspaceid = data().deepCopy(fields()[5].schema(), other.adspaceid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.price)) {
        this.price = data().deepCopy(fields()[6].schema(), other.price);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing WinNotice instance */
    private Builder(com.madhouse.ssp.avro.WinNotice other) {
            super(com.madhouse.ssp.avro.WinNotice.SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dspid)) {
        this.dspid = data().deepCopy(fields()[2].schema(), other.dspid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.impid)) {
        this.impid = data().deepCopy(fields()[3].schema(), other.impid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.mediaid)) {
        this.mediaid = data().deepCopy(fields()[4].schema(), other.mediaid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.adspaceid)) {
        this.adspaceid = data().deepCopy(fields()[5].schema(), other.adspaceid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.price)) {
        this.price = data().deepCopy(fields()[6].schema(), other.price);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'time' field */
    public java.lang.Long getTime() {
      return time;
    }
    
    /** Sets the value of the 'time' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setTime(long value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'time' field has been set */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'time' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.Integer getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setStatus(int value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'status' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearStatus() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'dspid' field */
    public java.lang.Long getDspid() {
      return dspid;
    }
    
    /** Sets the value of the 'dspid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setDspid(long value) {
      validate(fields()[2], value);
      this.dspid = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'dspid' field has been set */
    public boolean hasDspid() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'dspid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearDspid() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'impid' field */
    public java.lang.String getImpid() {
      return impid;
    }
    
    /** Sets the value of the 'impid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setImpid(java.lang.String value) {
      validate(fields()[3], value);
      this.impid = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'impid' field has been set */
    public boolean hasImpid() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'impid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearImpid() {
      impid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'mediaid' field */
    public java.lang.Long getMediaid() {
      return mediaid;
    }
    
    /** Sets the value of the 'mediaid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setMediaid(long value) {
      validate(fields()[4], value);
      this.mediaid = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'mediaid' field has been set */
    public boolean hasMediaid() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'mediaid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearMediaid() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'adspaceid' field */
    public java.lang.Long getAdspaceid() {
      return adspaceid;
    }
    
    /** Sets the value of the 'adspaceid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setAdspaceid(long value) {
      validate(fields()[5], value);
      this.adspaceid = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'adspaceid' field has been set */
    public boolean hasAdspaceid() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'adspaceid' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearAdspaceid() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.lang.Integer getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public com.madhouse.ssp.avro.WinNotice.Builder setPrice(int value) {
      validate(fields()[6], value);
      this.price = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'price' field */
    public com.madhouse.ssp.avro.WinNotice.Builder clearPrice() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public WinNotice build() {
      try {
        WinNotice record = new WinNotice();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Long) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.Integer) defaultValue(fields()[1]);
        record.dspid = fieldSetFlags()[2] ? this.dspid : (java.lang.Long) defaultValue(fields()[2]);
        record.impid = fieldSetFlags()[3] ? this.impid : (java.lang.String) defaultValue(fields()[3]);
        record.mediaid = fieldSetFlags()[4] ? this.mediaid : (java.lang.Long) defaultValue(fields()[4]);
        record.adspaceid = fieldSetFlags()[5] ? this.adspaceid : (java.lang.Long) defaultValue(fields()[5]);
        record.price = fieldSetFlags()[6] ? this.price : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
